### ISSUE TITLE
RD argument in store unused

### ISSUE THREAD

**Issue by arichardson** [riscv/riscv-zalasr#3]
I don't see this being used, and the sail code has it hardcoded so I believe this should be removed from the documentation?

**Comment by mehnadnerd** [comment]
That is correct, it should be addressed in https://github.com/mehnadnerd/riscv-zalasr/releases/tag/v0.0.4.

**Comment by mehnadnerd** [comment]
(commit https://github.com/mehnadnerd/riscv-zalasr/commit/f2506250bef326c1ca24a76aab79de3039c42106)
