### ISSUE TITLE
Wording and RESERVED encodings: why "should not", not "must not"?

### ISSUE THREAD

**Issue by a4lg** [riscv/riscv-zalasr#4]
> RV32 should not implement the d and q variants and RV64 should not implement the q variant.

I'm not sure why they use "should not", not "must not".

If you would like to leave *wider than XLEN* variants (e.g. `ld.aq` on RV32), I think you need to (at least) describe "over XLEN handling" on store-release operations but... looking at the SAIL code, I think "wider than XLEN" is not considered.

If my understandings are correct, changing "should not" to "must not" here will reflect your intent as in the SAIL code (e.g. `ld.aq` is not implemented in RV32).

**Comment by mehnadnerd** [comment]
You are right. I've corrected this in https://github.com/mehnadnerd/riscv-zalasr/commit/321cea1dcc1cf53a7ebee4a431300f3c5ff6fe31.
