### ISSUE TITLE
Dependency (clarification): is `Zalasr` depend on `A`?

### ISSUE THREAD

**Issue by a4lg** [riscv/riscv-zalasr#5]
Although this extension is an atomic extension, it is not sure whether this is based on the `A` extension.

For instance, `Zacas` had a good reason to add the `A` extension to the dependency (because it adds AMO PMAs that depend on `AMOArithmetic` level which is a part of the `A` extension).

But since this is not `Zacas` and there's no direct clue whether adding the `A` extension to the dependency of this `Zalasr` extension.
So, this is not a request to add `A` to the dependency but rather a question (clarification).

If this extension should depend on `A`, riscv/riscv-zacas#8 will be helpful.

**Comment by mehnadnerd** [comment]
This extension does not depend on the A extension.

**Comment by a4lg** [comment]
I'm happy to hear that.
